[package]
name = "decision-record"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
regex = "1"
lazy_static = "1.3.0"
glob = "0.3.0"
pathdiff = "0.2.1"
slug = "0.1.4"
chrono = "0.4"