# Based on https://alican.codes/rust-github-actions

name: Build Binaries
on: 
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build and prepare for releases
        run: |
          cargo build --all --release && \
          strip target/release/decision-record && \
          chmod +x target/release/decision-record && \
          mkdir -p .package/usr/bin && \
          cp target/release/decision-record target/release/decision-record_amd64 && \
          cp target/release/decision-record .package/usr/bin/decision-record

      - name: Build .deb
        uses: jiro4989/build-deb-action@v2
        with:
          package: decision-record
          package_root: .package
          maintainer: JonTheNiceGuy
          version: ${{ github.ref }}
          arch: 'amd64'
          desc: 'Decision Record script, from https://github.com/DecisionRecords/rust-decision-records'

      - name: Build .rpm
        uses: jiro4989/build-rpm-action@v2
        with:
          summary: 'Decision Record script'
          package: decision-record
          package_root: .package
          maintainer: JonTheNiceGuy
          version: ${{ github.ref }}
          arch: 'x86_64'
          desc: 'Decision Record script, from https://github.com/DecisionRecords/rust-decision-records'

      - name: Release binary and packages
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            target/release/decision-record_amd64
            *.deb
            *.rpm

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Release binary
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            target/release/decision-record.exe

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cargo build --all --release && strip target/release/decision-record && mv target/release/decision-record target/release/decision-record_darwin

      - name: Release binary
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            target/release/decision-record_darwin